version: '3.9'

services:
  web:
    build: .
    command: ./wait-for-it.sh db:5432 -- ./docker-entrypoint.sh
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - redis
      - db
    restart: on-failure

  db:
    image: postgres:12.11
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=${SUPPORT_DB_NAME}
      - POSTGRES_USER=${SUPPORT_DB_USER}
      - POSTGRES_PASSWORD=${SUPPORT_DB_PASSWORD}
    volumes:
      - postgresdata:/var/lib/postgresql  

  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redisdata:/data

  celery:
    build: .
    command: celery -A supportapp worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app

  tests:
    build: .
    command: ./wait-for-it.sh db:5432 -- ptw
    depends_on:
      - redis
      - db
    tty: true
    volumes:
      - .:/app

volumes:
  postgresdata:
  redisdata:  