# Generated by Django 4.0.5 on 2022-06-30 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_ticket_options_ticket_last_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['last_update']},
        ),
    ]
