# Generated by Django 4.0.5 on 2022-07-01 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_ticket_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='message_body',
            new_name='message',
        ),
    ]
