# Generated by Django 4.0.6 on 2022-07-12 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('timestamp',)},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='last_update',
        ),
    ]
