# Generated by Django 4.0.6 on 2022-07-12 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_ticket_reply_alter_reply_ticket_alter_ticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='support.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='support.reply'),
        ),
    ]
