# Generated by Django 4.0.6 on 2022-07-13 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_alter_reply_options_remove_ticket_reply_reply_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='support.ticket'),
        ),
    ]
