# Generated by Django 4.0.6 on 2022-07-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_alter_reply_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('updated_at',)},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
