# Generated by Django 4.0.6 on 2022-07-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0011_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['updated_at']},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('U', 'Unsolved'), ('F', 'Frozen'), ('S', 'Solved')], default='U', max_length=1),
        ),
    ]
